title: erlk1m
author: Erlkim
email: halo@erlkim.com
url: https://erlkim.com
#baseurl: "" 
description: > # this means to ignore newlines until "show_exerpts:"
  Biarlah jika ada orang yang merendahkan ataupun mencaci diri kita.
  </br>Anggap saja hanya sehembus angin yang berlalu.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 3
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: erlkim-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://soundcloud.com/erlkim
      icon: soundcloud
      color: orange
    - url: https://twitter.com/erlkim
      icon: twitter-square
      color: cyan
    - url: https://erlkim.itch.io
      icon: itch-io
      color: red
    - url: https://www.twitch.tv/
      icon: twitch
      color: purple
    - url: https://www.youtube.com/
      icon: youtube
      color: red
    - url: https://github.com/erlkim
      icon: github-square
      color: yellow

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  avatar_source: local
  avatar_path: /assets/avatar.gif

# Build settings
Theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jekyll-admin

collections:
  posts:
    output: true
    sidebar_label: News

